# Generated by Clean Architecture refactor

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0002_purchaseaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('event_type', models.CharField(choices=[('AddToCart', 'Add To Cart'), ('ClickProduct', 'Click Product'), ('PlaceOrder', 'Place Order')], max_length=50)),
                ('product_id', models.IntegerField(db_index=True)),
                ('product_variant_id', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'tracking_events',
            },
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['event_type', 'created_at'], name='tracking_event_type_time_idx'),
        ),
        migrations.AddIndex(
            model_name='trackingevent',
            index=models.Index(fields=['user_id', 'created_at'], name='tracking_event_user_time_idx'),
        ),
    ]
