# Generated by Clean Architecture cleanup

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking_app', '0003_trackingevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchHistory',
        ),
    ]
