# Generated by Clean Architecture refactor

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_order_item_variant_and_shipment_tracking'),
    ]

    operations = [
        migrations.AlterModelTable(name='shipmenttracking', table='ship_tracking'),
    ]
