# Generated by Clean Architecture cleanup

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_ship_tracking_table_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='variant_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shipmenttracking',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('confirmed', 'Confirmed'), ('preparing', 'Preparing'), ('shipped', 'Shipped'), ('delivering', 'Delivering'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('failed', 'Failed'), ('returned', 'Returned')], default='created', max_length=30),
        ),
    ]
