# Generated by Clean Architecture refactor

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0002_payment_method_and_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentlog',
            name='status',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
