# Generated by Django 4.2.7 on 2026-04-04 14:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OutboxMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=255)),
                ('aggregate_id', models.CharField(db_index=True, max_length=255)),
                ('payload', models.JSONField()),
                ('correlation_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('published', 'Published'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('last_retry_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'outbox_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='outbox_mess_status_74979f_idx'), models.Index(fields=['event_type', 'created_at'], name='outbox_mess_event_t_591fd8_idx')],
            },
        ),
    ]
