# Generated by Clean Architecture refactor

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_rbac_and_address'),
    ]

    operations = [
        migrations.AlterModelTable(name='customer', table='user'),
        migrations.AlterModelTable(name='permission', table='permission'),
        migrations.AlterModelTable(name='role', table='role'),
        migrations.AlterModelTable(name='rolepermission', table='role_permission'),
        migrations.AlterModelTable(name='address', table='address'),
    ]
