# Generated by Django 4.2.7 on 2026-04-05 03:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(db_index=True)),
                ('customer_id', models.IntegerField(db_index=True)),
                ('product_type', models.CharField(max_length=20)),
                ('product_id', models.IntegerField()),
                ('product_name', models.CharField(max_length=255)),
                ('stars', models.IntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'ratings',
                'unique_together': {('order_id', 'product_type', 'product_id')},
            },
        ),
    ]
