# Generated by Clean Architecture refactor

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='order_item_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='rating',
            name='product_variant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
