# Generated by Django 4.2.7 on 2026-04-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(default='box', help_text='FontAwesome icon name', max_length=50),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='dimensions',
            field=models.CharField(help_text='LxWxH', max_length=255),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='ram',
            field=models.IntegerField(help_text='RAM in GB'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='battery',
            field=models.IntegerField(help_text='Battery capacity in mAh'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='shoe_type',
            field=models.CharField(help_text='Sneaker, Boots, Formal, etc.', max_length=50),
        ),
    ]
